/**
 * @file Seed keywords for the twentyq game.
 *
 * Just the target word. Category + initial hint are generated by the LLM at
 * round start (see ai-client.generateRoundStart). Add any noun here — the
 * model figures out the right category and produces a cryptic opening clue.
 */

/** @type {string[]} */
export const SEEDS = [
  // instruments
  "guitar",
  "piano",
  "drum",
  "violin",
  "flute",
  "trumpet",
  "organ",
  "harmonica",
  // animals
  "elephant",
  "dolphin",
  "eagle",
  "kangaroo",
  "octopus",
  "penguin",
  "tiger",
  "horse",
  "snake",
  "owl",
  // food
  "pizza",
  "sushi",
  "burger",
  "ramen",
  "taco",
  "pho",
  "curry",
  "salad",
  "chocolate",
  "cheese",
  // vehicles
  "bicycle",
  "car",
  "airplane",
  "boat",
  "train",
  "motorcycle",
  "helicopter",
  "submarine",
  // sports
  "soccer",
  "basketball",
  "tennis",
  "swimming",
  "boxing",
  "golf",
  "chess",
  "skiing",
  // household items
  "refrigerator",
  "microwave",
  "vacuum",
  "toaster",
  "kettle",
  "blender",
  "lamp",
  "sofa",
  "mirror",
  "broom",
];

/**
 * Pick one target at random.
 * @param {() => number} [rng]  — defaults to Math.random; tests inject deterministic rng.
 * @returns {string}
 */
export function getRandomSeed(rng = Math.random) {
  const i = Math.floor(rng() * SEEDS.length);
  return SEEDS[Math.min(i, SEEDS.length - 1)];
}
