/**
 * @file Target-word pool for the doantu module (Vietnamese).
 *
 * Data lives in the sibling `words-data.js` (auto-generated by
 * `scripts/build-doantu-words.js` from duyet/vietnamese-wordlist's
 * Viet22K list, lowercased + deduped).
 *
 * API mirrors wordle/loldle and semantle's english sibling:
 *   `LINE_COUNT`  — total entries
 *   `randomLine()` — uniform random pick
 *   `getLine(n)`  — read the nth entry (alphabetical rank in the source list)
 */

import LINES from "./words-data.js";

export const LINE_COUNT = LINES.length;

/** @param {number} n @returns {string | undefined} */
export function getLine(n) {
  return LINES[n];
}

/** @returns {string} */
export function randomLine() {
  return LINES[Math.floor(Math.random() * LINE_COUNT)];
}
