/**
 * @file Target-word pool for the doantu module (Vietnamese).
 *
 * Data lives in the sibling `words-data.js` (auto-generated by
 * `scripts/build-doantu-words.js` from duyet/vietnamese-wordlist's
 * Viet22K list, lowercased + deduped).
 */

import LINES from "./words-data.js";

/** @returns {string} */
export function randomLine() {
  return LINES[Math.floor(Math.random() * LINES.length)];
}
