allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@remotion/bundler@4.0.485'
  - '@remotion/canvas-capture@4.0.485'
  - '@remotion/compositor-darwin-arm64@4.0.485'
  - '@remotion/compositor-darwin-x64@4.0.485'
  - '@remotion/compositor-linux-arm64-gnu@4.0.485'
  - '@remotion/compositor-linux-arm64-musl@4.0.485'
  - '@remotion/compositor-linux-x64-gnu@4.0.485'
  - '@remotion/compositor-linux-x64-musl@4.0.485'
  - '@remotion/compositor-win32-x64-msvc@4.0.485'
  - '@remotion/licensing@4.0.485'
  - '@remotion/media-parser@4.0.485'
  - '@remotion/media-utils@4.0.485'
  - '@remotion/paths@4.0.485'
  - '@remotion/player@4.0.485'
  - '@remotion/renderer@4.0.485'
  - '@remotion/shapes@4.0.485'
  - '@remotion/streaming@4.0.485'
  - '@remotion/studio-shared@4.0.485'
  - '@remotion/studio@4.0.485'
  - '@remotion/timeline-utils@4.0.485'
  - '@remotion/web-renderer@4.0.485'
  - '@remotion/zod-types@4.0.485'
  - '@vitest/expect@4.1.10'
  - '@vitest/mocker@4.1.10'
  - '@vitest/pretty-format@4.1.10'
  - '@vitest/runner@4.1.10'
  - '@vitest/snapshot@4.1.10'
  - '@vitest/spy@4.1.10'
  - '@vitest/utils@4.1.10'
  - remotion@4.0.485
  - vitest@4.1.10
