/**
 * @file Target-word pool for the semantle module.
 *
 * Data lives in the sibling `words-data.js` (auto-generated by
 * `scripts/build-semantle-words.js` from google-10000-english, normalized
 * to lowercase + deduped but otherwise unfiltered).
 *
 * API mirrors the "count, random index, read line" access pattern:
 *   `LINE_COUNT`  — how many entries are in the dictionary
 *   `randomLine()` — pick a uniformly-random entry
 *   `getLine(n)`  — read the nth entry (n is the frequency rank)
 */

import LINES from "./words-data.js";

export const LINE_COUNT = LINES.length;

/** @param {number} n @returns {string | undefined} */
export function getLine(n) {
  return LINES[n];
}

/** @returns {string} */
export function randomLine() {
  return LINES[Math.floor(Math.random() * LINE_COUNT)];
}

// Backwards-compat alias for earlier callers.
export { randomLine as pickFromPool };
