/**
 * @file Target-word pool for the semantle module.
 *
 * Data lives in the sibling `words-data.js` (auto-generated by
 * `scripts/build-semantle-words.js` from google-10000-english, normalized
 * to lowercase + deduped but otherwise unfiltered).
 */

import LINES from "./words-data.js";

/** @returns {string} */
export function randomLine() {
  return LINES[Math.floor(Math.random() * LINES.length)];
}
