/**
 * @file Target-word pool for the semantle module.
 *
 * The raw dictionary lives in `words-data.js` (auto-generated by
 * `scripts/build-semantle-words.js` from the public google-10000-english
 * list, filtered to 4–10 ASCII letters with the top-200 most frequent
 * function words stripped). This module just exposes the list and a
 * uniform random pick so api-client.js can stay focused on HTTP.
 */

import WORDS from "./words-data.js";

export const TARGET_POOL = WORDS;

/** @returns {string} — a random lowercase word from the pool. */
export function pickFromPool() {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}
